---
# tasks file for redis

- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Configure Redis from template
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0644'
  notify:
    - Restart Redis

- name: Ensuring that redis group exists in system
  group:
    name: "redis"
    state: present
  become: yes

- name: Ensuring that redis user exists in system
  user:
    name: "redis"
    group: "redis"
    shell: /bin/bash
    createhome: no
    system: yes
    state: present
    password: "{{ '1234' | password_hash('sha512') }}"
  become: yes

- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes
